name: Publish to Test Environment

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
        working-directory: ./bwcom
      - run: npm run build
        working-directory: ./bwcom
        
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Angular Build output
          path: ./bwcom/dist/bwcom
          retention-days: 5
