name: Publish updates to Prod Environment

on:
  workflow_dispatch:
  push:
    tags: ['v**']

jobs:
  deploy_to_prod:

    runs-on: ubuntu-latest

    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        working-directory: ./bwcom-cdk
        run: dotnet restore src
      - name: Build CDK
        working-directory: ./bwcom-cdk
        run: dotnet build src

      - name: Deploy BwcomProd
        working-directory: ./bwcom-cdk
        run: |
          npm install -g aws-cdk
          cdk deploy ProdDeployment --require-approval never

      - name: Copy files from test to prod with the AWS CLI
        run: |
          aws s3 sync s3://test.brentwoodle.com s3://brentwoodle.com
      - name: Invalidate CloudFront Cache
        run: |
          distro=$(aws ssm get-parameter --name "/bwcom/prod/distribution-id" --query "Parameter.Value" --output text)
          aws cloudfront create-invalidation --distribution-id $distro --paths '/*'
    
      - name: Update Version
        run: |
          version=$(git rev-parse --short ${{ github.ref_name }})
          aws ssm put-parameter --name "/bwcom/prod/version" --value $version --type String